version: "3"

services:

  mftp:
    build:
      context: ./mftp
      dockerfile: Dockerfile
    image: proffapt/mftp
    container_name: mftp
    command: $MFTP_MODE
    volumes:
      - $MFTP_CONFIG/env.py:/mftp/env.py
      - $MFTP_CONFIG/token.json:/mftp/token.json 
      - $MFTP_CONFIG/credentials.json:/mftp/credentials.json
      - $MFTP_CONFIG/mail_send_token.json:/mftp/mail_send_token.json
      - $MFTP_CONFIG/mail_send_creds.json:/mftp/mail_send_creds.json
      - $MFTP_CONFIG/.lsnif:/mftp/.lsnif
      - $MFTP_CONFIG/.session:/mftp/.session
    
  mftp-doctor:
    build:
      context: ./mftp-doctor
      dockerfile: Dockerfile
    image: proffapt/mftp-doctor
    container_name: mftp-doctor
    command: ${DOCTOR_MODE:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCTOR_CONFIG/env.py:/mftp-doctor/env.py

  mftp-ntfy:
    build:
      context: ./mftp-ntfy
      dockerfile: Dockerfile
    container_name: mftp-ntfy
    environment:
      - TZ=IST
    volumes:
      - mftp-ntfy-cache:/var/cache/ntfy
    ports:
      - "8000:8000"
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8000/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped

volumes:
  mftp-ntfy-cache: