
version: "3"

services:

  mftp-doctor:
    build:
      context: .
      dockerfile: Dockerfile
    image: proffapt/mftp-doctor
    container_name: mftp-doctor
    command: ${DOCTOR_MODE:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCTOR_CONFIG/env.py:/mftp-doctor/env.py
