name: Continuous Deployment Pipeline

on:
    push:
        branches:
            - "main"
        paths-ignore:
            - "**.md"
            - "LICENSE"

jobs:
    dockerhub:
        name: Publish Docker Image(s) to Dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Cache Docker layers for MFTP Doctor
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache-mftp-doctor
                  key: ${{ runner.os }}-buildx-mftp-doctor-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-mftp-doctor-

            - name: Build & Push MFTP Doctor
              uses: docker/build-push-action@v5
              with:
                  context: ./mftp-doctor/
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/mftp-doctor:latest
                  cache-from: type=local,src=/tmp/.buildx-cache-mftp-doctor
                  cache-to: type=local,dest=/tmp/.buildx-cache-mftp-doctor-new,mode=max

            - name: Move MFTP Doctor cache
              run: |
                  rm -rf /tmp/.buildx-cache-mftp-doctor
                  mv /tmp/.buildx-cache-mftp-doctor-new /tmp/.buildx-cache-mftp-doctor

            - name: Cache Docker layers for MFTP
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache-mftp
                  key: ${{ runner.os }}-buildx-mftp-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-mftp-

            - name: Build & Push MFTP
              uses: docker/build-push-action@v5
              with:
                  context: ./mftp/
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/mftp:latest
                  cache-from: type=local,src=/tmp/.buildx-cache-mftp
                  cache-to: type=local,dest=/tmp/.buildx-cache-mftp-new,mode=max

            - name: Move MFTP cache
              run: |
                  rm -rf /tmp/.buildx-cache-mftp
                  mv /tmp/.buildx-cache-mftp-new /tmp/.buildx-cache-mftp

    push:
        name: Push Code Stage
        needs: dockerhub
        runs-on: ubuntu-latest

        steps:
            - name: Sync local repo with remote repo
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/"
                      sudo git fetch origin
                      sudo git reset --hard origin/main

    pull:
        name: Pull Image Stage
        needs: push
        runs-on: ubuntu-latest

        steps:
            - name: Pull the latest images(s)
              uses: appleboy/ssh-action@master
              env:
                  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
              with:
                  host: ${{ secrets.SSH_HOSTNAME }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
                  envs: PROJECT_DIR
                  script_stop: true
                  script: |
                      cd "${PROJECT_DIR}/"
                      sudo docker compose pull
